schemaVersion: 2.2.0
metadata:
  name: demo
  namespace: sonti-ka-dev
components:
  - container:
      image: quay.io/devfile/universal-developer-image:ubi8-d071837
      env:
        - name: CONFIGURATION
          value: Debug
        - name: HTTP_PROXY
          value: https://127.0.0.1:8080
    name: developer
commands:
   - id: create a dir
     exec:
        label: "create a dir"
        component: builder
        workingDir: ${PROJECTS_ROOT}
        commandLine: |
            mkdir output;
