schemaVersion: 2.2.2
metadata:
  name: demo
  namespace: sonti-ka-dev
components:
  - container:
      image: quay.io/devfile/universal-developer-image:ubi8-d071837
    name: developer
commands:
   - id: setenv
     exec:
        label: "set env variables"
        component: developer
        workingDir: ${PROJECTS_ROOT}/devspaces
        commandLine: |
            export name=karthik;
            export demo=test
events:
  postStart:
    - "setenv"
